### ISSUE TITLE
Tag stable release

### ISSUE THREAD

**Issue by bramstroker** [Bacon/BaconStringUtils#11]
@DASPRiD Could you please tag a new version of this package? We depend on it for our application and I'm just in the process of removing minimum-stability: dev from our composer to only depend on stable releases.
We use the `SlugifierFactory` but this is not part of the latest release yet.
thanks.

**Comment by DASPRiD** [comment]
Hi, I've tagged a 1.1.0 release with the new features in master. Although this library definitely needs an update to get rid of the older ZF2 stuff eventually, but that's up for a 2.0.0 release.

**Comment by bramstroker** [comment]
Thanks a lot for the fast action. This is what makes the PHP community awesome.
