### ISSUE TITLE
Tag BaconStringUtils

### ISSUE THREAD

**Issue by juriansluiman** [Bacon/BaconStringUtils#3]
Hi @DASPRiD,

Can you make a 0.1.0 or 1.0.0 version for BaconStringUtils? I depend on this module now, but because only dev-master is available, it's quite hard to keep all the packages using stable releases. I don't really care how the tag is called, as long as there is a tag recognized by composer ;)

**Comment by DASPRiD** [comment]
Sure I think I can do that. Let me think about a useful version schema :)

**Comment by DASPRiD** [comment]
Current version tagged as 1.0.0
